[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "modefilter"
authors = [{ name = "Sherman Lo", email = "sherman.ip.10@alumni.ucl.ac.uk" }]
version = "2.4.1"
dependencies = ["numpy", "scipy"]

[project.optional-dependencies]
cuda11x = ["cupy-cuda11x"]
cuda12x = ["cupy-cuda12x"]
napari = ["napari[all]"]

[project.entry-points."napari.manifest"]
modefilter = "modefilter:napari.yaml"

[tool.setuptools.packages.find]
where = ["python"]

[tool.setuptools.package-data]
"*" = ["*.ptx"]

[tool.ruff]
line-length = 80
indent-width = 4

[tool.ruff.lint.pydocstyle]
convention = "google"
