[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "modefilter"
authors = [{ name = "Sherman Lo", email = "sherman.ip.10@alumni.ucl.ac.uk" }]
version = "2.5.0"
dependencies = ["numpy", "scipy"]

[project.optional-dependencies]
cuda11x = ["cupy-cuda11x"]
cuda12x = ["cupy-cuda12x"]
cuda13x = ["cupy-cuda13x"]
napari = ["napari[all]"]
test = ["pytest"]

[project.entry-points."napari.manifest"]
modefilter = "modefilter:napari.yaml"

[tool.setuptools.packages.find]
where = ["src/python"]

[tool.setuptools.package-data]
"*" = ["*.ptx"]

[tool.pytest]
testpaths = ["tests/pytest"]

[tool.ruff]
include = ["pyproject.toml", "python/**/*.py", "tests/**/*.py"]
line-length = 80
indent-width = 4

[tool.ruff.lint.pydocstyle]
convention = "google"
